language: node_js
node_js: 8.11.1
cache:
  directories:
    - node_modules
install:
  yarn
script:
  yarn build:ghpages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  fqdn: gameoflife.xyz
  on:
    branch: master
